#pragma once

class CAction65_Parser
{
public:
	CAction65_Parser();
	virtual ~CAction65_Parser();
	BOOL Create();
	//------------------------------
	//      Parsing Methods
	//------------------------------
	CAction65Lexer::Token Action65(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Modules(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Modules_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token PROCroutine(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token PROCroutine_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FUNCroutine(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FUNCroutine_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcDef(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FuncDef(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcBody(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcBody_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcDecl(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FuncDecl(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcIdent(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FuncIdent(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Statements(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Begin(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcCall(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ProcCall_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ForStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ForStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token IfStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token IfStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token WhileStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token WhileStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token DoStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token DoStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token EXITstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token EXITstmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RetStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RetStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CodeBlock(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CodeBlock_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token UntillStmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token UntillStmt_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Assignment(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ASSIGNstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token PROCstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token If(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ThenPart(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ThenPart_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ElseIfPart(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token DOstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token UNTILLstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token WhileLoop(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FORstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Start(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Finish(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token STEPoption(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CODEblock(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CODEblock_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RETURNstmt(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ArithExpr(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token LogicalOR_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token LogicalAND(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token LogicalAND_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RelOperation(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RelOperation_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RelEquals(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RelEquals_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseOR(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseOR_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseAND(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseAND_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseXOR(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BitwiseXOR_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token AddExpr(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token AddExpr_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ShifExpr(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ShiftExpr_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token MultExpr(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token MultExpr_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Unary(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Factor(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FUNCcall(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token IdentList(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token IdentList_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token FundType(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token OptModifier(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ParamList(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ParamList_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Param(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token VarDecls(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token SysDecls(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token SysDecls_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token SysDecl(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token VarList(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token VarList_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token VarName(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token OptInit(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token DefList(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token DefList_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Def(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RecIdent(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RecField(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RecFieldList(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token RecFieldList_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Modifier(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token ArrayStuff(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token OptArrayInit(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CompConst(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token CompConst_1(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token BaseCompConst(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token Ident(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token MemContents(CAction65Lexer::Token LookaHeadToken);
	CAction65Lexer::Token MemContentsType(CAction65Lexer::Token LookaHeadToken);
};
